AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  restApiName:
    Type: String
Resources: 
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref restApiName
  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      